[2024-11-22 23:19:48,743] #INFO     main.py:88 - __main__ - Starting the main event loop.
[2024-11-22 23:19:48,744] #INFO     main.py:50 - __main__ - Starting up
[2024-11-22 23:19:48,745] #INFO     main.py:53 - __main__ - Connecting routers
[2024-11-22 23:19:48,745] #INFO     main.py:57 - __main__ - Setting up middlewares
[2024-11-22 23:19:48,745] #INFO     main.py:58 - __main__ - Initializing bot
[2024-11-22 23:19:48,929] #INFO     main.py:68 - __main__ - Starting app
[2024-11-22 23:19:49,601] #INFO     main.py:73 - __main__ - Ready to use

       Started on  http://0.0.0.0:5000!
[2024-11-22 23:19:54,546] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:19:54 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:19:54,547] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854718 is handled. Duration 0 ms by bot id=803173072
[2024-11-22 23:20:04,523] #INFO     main.py:80 - __main__ - Shutdown bot session..
[2024-11-22 23:34:53,623] #ERROR    client.py:196 - nats.aio.client - nats: encountered error
Traceback (most recent call last):
  File "D:\PythonProject\taskiq_test\.venv\Lib\site-packages\nats\aio\client.py", line 1442, in _attempt_reconnect
    await self._transport.wait_closed()
  File "D:\PythonProject\taskiq_test\.venv\Lib\site-packages\nats\aio\transport.py", line 180, in wait_closed
    return await self._io_writer.wait_closed()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lex\AppData\Local\Programs\Python\Python312\Lib\asyncio\streams.py", line 361, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "C:\Users\Lex\AppData\Local\Programs\Python\Python312\Lib\asyncio\selector_events.py", line 1138, in _write_send
    n = self._sock.send(buffer)
        ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение
[2024-11-22 23:34:53,635] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:34:53 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:34:53,636] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:34:53 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:34:53,636] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854719 is not handled. Duration 0 ms by bot id=803173072
[2024-11-22 23:34:53,637] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854719 is not handled. Duration 0 ms by bot id=803173072
[2024-11-22 23:34:53,779] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:34:53 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:34:53,780] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854720 is not handled. Duration 0 ms by bot id=803173072
[2024-11-22 23:34:53,877] #INFO     main.py:82 - __main__ - Shutdown dp storage ..
[2024-11-22 23:35:44,942] #INFO     main.py:87 - __main__ - Starting the main event loop.
[2024-11-22 23:35:44,944] #INFO     main.py:49 - __main__ - Starting up
[2024-11-22 23:35:44,944] #INFO     main.py:52 - __main__ - Connecting routers
[2024-11-22 23:35:44,945] #INFO     main.py:56 - __main__ - Setting up middlewares
[2024-11-22 23:35:44,945] #INFO     main.py:57 - __main__ - Initializing bot
[2024-11-22 23:35:45,126] #INFO     main.py:67 - __main__ - Starting app
[2024-11-22 23:35:45,827] #INFO     main.py:72 - __main__ - Ready to use

       Started on  http://0.0.0.0:5000!
[2024-11-22 23:35:49,711] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:35:49 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:35:49,713] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854721 is handled. Duration 0 ms by bot id=803173072
[2024-11-22 23:36:51,393] #INFO     web_log.py:211 - aiohttp.access - 127.0.0.1 [22/Nov/2024:23:36:51 +0900] "POST /awh HTTP/1.0" 200 161 "-" "-"
[2024-11-22 23:36:51,394] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854722 is not handled. Duration 0 ms by bot id=803173072
[2024-11-23 00:17:36,810] #INFO     main.py:56 - __main__ - Starting the main event loop.
[2024-11-23 00:17:36,811] #INFO     main.py:38 - __main__ - Starting up
[2024-11-23 00:17:36,812] #INFO     main.py:41 - __main__ - Connecting routers
[2024-11-23 00:17:36,812] #INFO     main.py:45 - __main__ - Setting up middlewares
[2024-11-23 00:17:36,812] #INFO     main.py:46 - __main__ - Initializing bot
[2024-11-23 00:17:37,546] #INFO     dispatcher.py:527 - aiogram.dispatcher - Start polling
[2024-11-23 00:17:37,707] #INFO     dispatcher.py:341 - aiogram.dispatcher - Run polling for bot @CAHE4ekBot id=803173072 - 'SanechekBot'
[2024-11-23 00:17:54,001] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854723 is handled. Duration 0 ms by bot id=803173072
[2024-11-23 00:20:19,204] #INFO     main.py:56 - __main__ - Starting the main event loop.
[2024-11-23 00:20:19,205] #INFO     main.py:38 - __main__ - Starting up
[2024-11-23 00:20:19,206] #INFO     main.py:41 - __main__ - Connecting routers
[2024-11-23 00:20:19,206] #INFO     main.py:45 - __main__ - Setting up middlewares
[2024-11-23 00:20:19,206] #INFO     main.py:46 - __main__ - Initializing bot
[2024-11-23 00:20:19,921] #INFO     dispatcher.py:527 - aiogram.dispatcher - Start polling
[2024-11-23 00:20:20,069] #INFO     dispatcher.py:341 - aiogram.dispatcher - Run polling for bot @CAHE4ekBot id=803173072 - 'SanechekBot'
[2024-11-23 00:20:20,207] #ERROR    dispatcher.py:219 - aiogram.dispatcher - Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
[2024-11-23 00:20:20,208] #WARNING  dispatcher.py:221 - aiogram.dispatcher - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 803173072)
[2024-11-23 00:20:24,353] #ERROR    dispatcher.py:219 - aiogram.dispatcher - Failed to fetch updates - TelegramConflictError: Telegram server says - Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
[2024-11-23 00:20:24,353] #WARNING  dispatcher.py:221 - aiogram.dispatcher - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 803173072)
[2024-11-23 00:20:29,371] #INFO     dispatcher.py:233 - aiogram.dispatcher - Connection established (tryings = 1, bot id = 803173072)
[2024-11-23 00:20:29,373] #INFO     dispatcher.py:172 - aiogram.event - Update id=710854724 is handled. Duration 0 ms by bot id=803173072
[2024-11-23 00:20:35,513] #INFO     dispatcher.py:554 - aiogram.dispatcher - Polling stopped
[2024-11-23 00:20:35,778] #INFO     dispatcher.py:359 - aiogram.dispatcher - Polling stopped for bot @CAHE4ekBot id=803173072 - 'SanechekBot'
